AWSTemplateFormatVersion: 2010-09-09
Description: S3 provision

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: STD21021

  BucketSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 'BucketS3'
      Type: String
      Value: !Ref Bucket
    DependsOn: Bucket

  BucketArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 'BucketS3-Arn'
      Type: String
      Value: !GetAtt Bucket.Arn
    DependsOn: Bucket