name: CD

on:
  push:
    branches:
      - "main"
    paths:
      - "cf-stacks/storage-stack.yml"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation create-stack --stack-name MyStack --template-body cf-stacks/storage-stack.yml --region us-east-1 --capabilities CAPABILITY_IAM